---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/registrations":
    post:
      summary: Registers a new user
      tags:
      - Registrations
      parameters: []
      responses:
        '201':
          description: user registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                    required:
                    - id
                    - username
        '400':
          description: user not registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
