---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/registrations":
    post:
      summary: Registers a new user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                    required:
                    - id
                    - username
        '400':
          description: user not registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      username:
                        type: array
                        items:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        description: Username needed to create a new user.
  "/api/v1/sessions":
    post:
      summary: Logs a user in
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  username:
                    type: string
                  token:
                    type: string
        '401':
          description: user not registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      username:
                        type: array
                        items:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        description: A username of an existing user needed to sign in.
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
