default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workspace_reservation

test:
  <<: *default
  database: workspace_reservation_test

production:
  <<: *default
  database: workspace_reservation_live
