default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: youcan
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workspace_reservation

test:
  <<: *default
  database: workspace_reservation_test

production:
  <<: *default
  database: workspace_reservation_live
